### ISSUE TITLE
Log output is getting sent to .err

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen-infra#1]
Log output seems to only be getting sent to the err log file.

e.g. `nevergreen-staging.err` instead of `nevergreen-staging.log` which exists but is empty.

**Comment by joejag** [comment]
Going to resolve with #2

**Comment by GentlemanHal** [comment]
Has this been resolved? This might be something to do with it

> org.slf4j.simpleLogger.logFile - The output target which can be the path to a file, or the special values "System.out" and "System.err". Default is "System.err".

https://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html

We should probably change this either way?

**Comment by GentlemanHal** [comment]
I've switched Nevergreen to use logback so logs should be getting send to System out correctly now, more details at https://github.com/build-canaries/nevergreen/issues/221

**Comment by GentlemanHal** [comment]
Given we've completely changed how Nevergreen is hosted and deployed I'm going to close this.
