### ISSUE TITLE
Rotate logs

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen-infra#2]
The logs are getting huge, the production log file was over 16GB!

We should add some kind of log rotation and backup. Perhaps a daily rotation with 7 days worth of backups?

**Comment by joejag** [comment]
Added to /etc/logrotate.conf

```
/var/log/nevergreen-*.err {
    size 100M
    create 0660 root utmp
    copytruncate
    rotate 1
}
```
