### ISSUE TITLE
Install CI servers for testing

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen-infra#5]
- [GO CD](https://www.gocd.io/)
- [Jenkins](https://jenkins.io/)

**Comment by joejag** [comment]
What's involved with this? Do we want a real Go and Jenkins set up which we can target?

**Comment by GentlemanHal** [comment]
Ideally having real CI servers to test against, but it does seem like quite a lot of effort.

Perhaps we could start with extracting the CI stub server out of the Nevergreen codebase and deploy that as a separate service?
