### ISSUE TITLE
nevergreen.io availability

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen-infra#9]
We seem to have regular problems with nevergreen.io being unavailable.

Would switching to [Google Container Engine](https://cloud.google.com/container-engine/) or [AWS Container Service](https://aws.amazon.com/documentation/ecs/) give us better uptime?

**Comment by rahulmr** [comment]
:+1:  for Google Containers. They have good discounts when it comes to billing.
You may think of adding a donation link on the page for funding the cost of GCP.

**Comment by rahulmr** [comment]
I think even heroku can be good option but not sure about the billing.

**Comment by joejag** [comment]
Previously we were on one digital ocean machine, running one instance of nevergreen.

We've moved to one ec2 box, with two instances of nevergreen running.

Our uptime, according to Pingdom is 99.46% for the last two months (12 hours of downtime).

I'll come back in a month and share the new uptime,

**Comment by joejag** [comment]
![image](https://user-images.githubusercontent.com/57625/36866849-6282fdbc-1d8b-11e8-9235-e6d68459ae06.png)

**Comment by GentlemanHal** [comment]
I'm happy for this to be closed if you are @joejag

**Comment by joejag** [comment]
Yeah. If it gets cheaper to run three instances of something with https termination then a single ec2 box then let's reopen. Otherwise, I think we are good.

**Comment by rahulmr** [comment]
Found a small issue with redirection. nevergreen.io should redirect to https://nevergreen.io 
Will be happy to see this fixed :)
